"""empty message

Revision ID: eddf72579b47
Revises: a2ad566d7489
Create Date: 2023-02-20 11:15:23.982536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddf72579b47'
down_revision = 'a2ad566d7489'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
